eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}:@project.version@
    prefer-ip-address: true

server:
  port: 8804

spring:
  application:
    name: vedio-http

# ¿ªÆôÈÛ¶Ï
feign:
  hystrix:
    enabled: true